apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tq3qrs1qm-python
  janus-idp.io/tekton: tq3qrs1qm-python
  backstage.io/kubernetes-id: tq3qrs1qm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tq3qrs1qm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
