apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tq3qrs1qm-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tq3qrs1qm-python 
  name: tq3qrs1qm-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tq3qrs1qm-python 
